import HomeLayout from "@/components/layout/homeLayout/HomeLayout";
import { ToastContainer, toast , Bounce } from 'react-toastify';  
import 'react-toastify/dist/ReactToastify.css';  


import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" dir="rtl">
      <body 
        className={`antialiased overflow-x-hidden`}
      >
        <HomeLayout>
         {children}
        </HomeLayout>
        <ToastContainer 
          position="bottom-right"
          autoClose={5000}
          hideProgressBar={false}
          newestOnTop={false}
          closeOnClick={false}
          rtl={false}
          pauseOnFocusLoss
          theme="light"
          transition={Bounce}
        />
      </body>
    </html>
  );
}
