import HomeLayout from "@/components/layout/homeLayout/HomeLayout";

import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" dir="rtl">
      <body 
        className={`antialiased overflow-x-hidden`}
      >
        <HomeLayout>
         {children}
        </HomeLayout>
      </body>
    </html>
  );
}
